### ISSUE TITLE
color keywords will convert all text 

### ISSUE THREAD

**Issue by leeluolee** [leeluolee/mcss#1]
color keywords will convert all text 

like 

``` css
body{
   white: white;
}
```

convert to

``` css
body{
    #ffffff: #ffffff;
}
```

The correct result is only convert the value will use for operate color , but not other ident

``` css
body{
   white: #fff;
}
```
