### ISSUE TITLE
@abstract的文件中再次@import会引入css规则

### ISSUE THREAD

**Issue by fengzilong** [leeluolee/mcss#16]
index.mcss

```css
@abstract './a.mcss';
```

a.mcss

```css
@import './b.mcss';
```

b.mcss

```css
div { color: #000; }
```

以index.mcss为入口进行打包，结果是`div { color: #000; }`

期望的现象：打包出来为不包含任何css规则
