### ISSUE TITLE
@extend不能从同一个class的多个地方继承

### ISSUE THREAD

**Issue by rainfore** [leeluolee/mcss#9]
```css
.u-btn {left: 20px;}
.u-btn {right: 40px;}

.u-btn-extend {@extend .u-btn}
```

会生成
```css
.u-btn {left: 20px;}
.u-btn.u-btn-extend {right: 40px;}
```

上一个class被忽略。
